# Generated by Django 2.1.5 on 2020-02-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_name_slug',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
