# Generated by Django 2.1.5 on 2020-02-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_user_organization_name_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_views',
            field=models.IntegerField(default=0, verbose_name='Просмотров'),
        ),
    ]
