# Generated by Django 2.1.5 on 2020-02-23 07:32

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, verbose_name='Порядок отображения')),
                ('image', models.ImageField(null=True, upload_to='banners/', verbose_name='Картинка')),
                ('big_text', models.CharField(max_length=255, null=True, verbose_name='Большой текст')),
                ('small_text', models.TextField(null=True, verbose_name='Маленький текст')),
                ('url_text1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Надпись на кнопке 1')),
                ('url_text2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Надпись на кнопке 2')),
                ('url_link1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на кнопке 1')),
                ('url_link2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на кнопке 2')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blackListType', models.CharField(choices=[('W', 'Исполнитель'), ('C', 'Заказчик')], default='W', max_length=2, verbose_name='Тип')),
                ('image', models.ImageField(null=True, upload_to='banners/', verbose_name='Картинка')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Логин, ник, фио')),
                ('name_slug', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('contacts', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Все возможные контакты')),
                ('why', models.TextField(null=True, verbose_name='Причина добаления в список')),
                ('moneyLost', models.IntegerField(null=True, verbose_name='Материальный ущерб')),
                ('profile', models.CharField(max_length=255, null=True, verbose_name='Ссылка на профиль(отзыв о) исполнителя/заказчика на сайте, где возник инциден')),
                ('file', models.FileField(upload_to='blacklist/', verbose_name='Загрузка переписки')),
                ('isAgreed', models.BooleanField(default=False, verbose_name='Устанавливая флажок я выражаю свое согласие на обработку персональных данных')),
                ('isModerated', models.BooleanField(default=False, verbose_name='Подтверждено?')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Заявка в черный список',
                'verbose_name_plural': 'Заявки в черный список',
            },
        ),
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='Почта')),
                ('text', models.TextField(null=True, verbose_name='Сообщение')),
                ('createdAt', models.DateField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Форма обратной связи',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Адрес')),
                ('phone', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Телефон')),
                ('email', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='EMail')),
                ('about_info', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст на страницу О нас')),
                ('slider1_text', models.CharField(max_length=255, null=True, verbose_name='Слайдер1 текст')),
                ('slider1_num', models.IntegerField(default=0, null=True, verbose_name='Слайдер1 Значание')),
                ('slider2_text', models.CharField(max_length=255, null=True, verbose_name='Слайдер2 текст')),
                ('slider2_num', models.IntegerField(default=0, null=True, verbose_name='Слайдер2 Значание')),
                ('slider3_text', models.CharField(max_length=255, null=True, verbose_name='Слайдер3 текст')),
                ('slider3_num', models.IntegerField(default=0, null=True, verbose_name='Слайдер3 Значание')),
                ('slider4_text', models.CharField(max_length=255, null=True, verbose_name='Слайдер4 текст')),
                ('slider4_num', models.IntegerField(default=0, null=True, verbose_name='Слайдер4 Значание')),
            ],
            options={
                'verbose_name': 'Контакты и О нас',
                'verbose_name_plural': 'Контакты и О нас',
            },
        ),
    ]
