# Generated by Django 2.1.5 on 2020-02-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='url',
        ),
        migrations.AddField(
            model_name='banner',
            name='big_text',
            field=models.CharField(max_length=255, null=True, verbose_name='Большой текст'),
        ),
        migrations.AddField(
            model_name='banner',
            name='small_text',
            field=models.CharField(max_length=255, null=True, verbose_name='Маленький текст'),
        ),
        migrations.AddField(
            model_name='banner',
            name='url_link1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на кнопке 1'),
        ),
        migrations.AddField(
            model_name='banner',
            name='url_link2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на кнопке 2'),
        ),
        migrations.AddField(
            model_name='banner',
            name='url_text1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Надпись на кнопке 1'),
        ),
        migrations.AddField(
            model_name='banner',
            name='url_text2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Надпись на кнопке 2'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(null=True, upload_to='banners/', verbose_name='Картинка'),
        ),
    ]
