# Generated by Django 2.1.5 on 2020-02-08 17:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20200206_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blackListType', models.CharField(choices=[('W', 'Исполнитель'), ('C', 'Заказчик')], default='W', max_length=2, verbose_name='Тип')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Логин, ник, фио')),
                ('contacts', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Все возможные контакты')),
                ('why', models.TextField(null=True, verbose_name='Причина добаления в список')),
                ('moneyLost', models.IntegerField(null=True, verbose_name='Материальный ущерб')),
                ('profile', models.CharField(max_length=255, null=True, verbose_name='Ссылка на профиль(отзыв о) исполнителя/заказчика на сайте, где возник инциден')),
                ('file', models.FileField(upload_to='blacklist/', verbose_name='Загрузка переписки')),
                ('isAgreed', models.BooleanField(default=False, verbose_name='Устанавливая флажок я выражаю свое согласие на обработку персональных данных')),
                ('isModerated', models.BooleanField(default=False, verbose_name='Подтверждено?')),
            ],
            options={
                'verbose_name': 'Заявка в черный список',
                'verbose_name_plural': 'Заявки в черный список',
            },
        ),
    ]
