# Generated by Django 2.1.5 on 2020-02-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_blacklist_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='small_text',
            field=models.TextField(null=True, verbose_name='Маленький текст'),
        ),
    ]
