# Generated by Django 2.1.5 on 2020-02-11 17:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20200211_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdTextPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Адрес')),
                ('phone', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Телефон')),
                ('email', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='EMail')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
