# Generated by Django 2.1.5 on 2020-02-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_adtextpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdTextPost',
            new_name='Contact',
        ),
    ]
