# Generated by Django 2.1.5 on 2020-02-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20200211_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='image',
            field=models.ImageField(null=True, upload_to='banners/', verbose_name='Картинка'),
        ),
    ]
