# Generated by Django 2.1.5 on 2020-02-12 17:00

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_blacklist_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакты и О нас', 'verbose_name_plural': 'Контакты и О нас'},
        ),
        migrations.AddField(
            model_name='contact',
            name='about_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст на страницу О нас'),
        ),
        migrations.AddField(
            model_name='contact',
            name='slider1_num',
            field=models.IntegerField(default=0, null=True, verbose_name='Слайдер1 Значание'),
        ),
        migrations.AddField(
            model_name='contact',
            name='slider1_text',
            field=models.CharField(max_length=255, null=True, verbose_name='Слайдер1 текст'),
        ),
        migrations.AddField(
            model_name='contact',
            name='slider2_num',
            field=models.IntegerField(default=0, null=True, verbose_name='Слайдер2 Значание'),
        ),
        migrations.AddField(
            model_name='contact',
            name='slider2_text',
            field=models.CharField(max_length=255, null=True, verbose_name='Слайдер2 текст'),
        ),
        migrations.AddField(
            model_name='contact',
            name='slider3_num',
            field=models.IntegerField(default=0, null=True, verbose_name='Слайдер3 Значание'),
        ),
        migrations.AddField(
            model_name='contact',
            name='slider3_text',
            field=models.CharField(max_length=255, null=True, verbose_name='Слайдер3 текст'),
        ),
        migrations.AddField(
            model_name='contact',
            name='slider4_num',
            field=models.IntegerField(default=0, null=True, verbose_name='Слайдер4 Значание'),
        ),
        migrations.AddField(
            model_name='contact',
            name='slider4_text',
            field=models.CharField(max_length=255, null=True, verbose_name='Слайдер4 текст'),
        ),
    ]
