# Generated by Django 2.1.5 on 2020-02-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_auto_20200212_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='name_slug',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
