# Generated by Django 2.1.5 on 2020-02-23 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advideopost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customuser.Company', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='adtextpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customuser.Company', verbose_name='Автор'),
        ),
    ]
