# Generated by Django 2.1.5 on 2020-02-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20200206_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advideopost',
            options={'verbose_name': 'Видео обьявление', 'verbose_name_plural': 'Видео обьявления'},
        ),
        migrations.AddField(
            model_name='adtextpost',
            name='is_published_at_index',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
        migrations.AddField(
            model_name='advideopost',
            name='is_published_at_index',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
        migrations.AlterField(
            model_name='adtextpost',
            name='name_slug',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adtextpost',
            name='page_description',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Описание страницы SEO'),
        ),
        migrations.AlterField(
            model_name='adtextpost',
            name='page_h1',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Тег H1'),
        ),
        migrations.AlterField(
            model_name='adtextpost',
            name='page_keywords',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Keywords SEO'),
        ),
        migrations.AlterField(
            model_name='adtextpost',
            name='page_title',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Название страницы SEO'),
        ),
        migrations.AlterField(
            model_name='advideopost',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Отображать  ?'),
        ),
        migrations.AlterField(
            model_name='advideopost',
            name='name_slug',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='advideopost',
            name='page_description',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Описание страницы SEO'),
        ),
        migrations.AlterField(
            model_name='advideopost',
            name='page_h1',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Тег H1'),
        ),
        migrations.AlterField(
            model_name='advideopost',
            name='page_keywords',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Keywords SEO'),
        ),
        migrations.AlterField(
            model_name='advideopost',
            name='page_title',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Название страницы SEO'),
        ),
    ]
