# Generated by Django 2.1.5 on 2020-02-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20200206_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advideopost',
            name='video_link',
            field=models.CharField(max_length=100, null=True, verbose_name='Видео ID'),
        ),
    ]
